### ISSUE TITLE
Option for enable cache

### ISSUE THREAD

**Issue by LeonardoGentile** [jin5354/axios-cache-plugin#5]
Hello, thank you for this!
I was wondering if it could be a good idea to add an option to the default axios option object to tell this plugin we want to enable/disable the cache for specific requests.

Right now for enabling the cache for a path we do this
```
wrappedAxios.__addFilter(/myPath/);
```

But I'd like something like this to exists:
```
wrappedAxios.get('/myPath', {cache: true});
```
Wouldn't this be more clean?

The two options can live well together, telling that the option `{cache: true}` will always have priority. 
Also The same would be similar for `cache: false`, meaning that even `/myPath` is added to the filter of what should be cached, if we do this
```
wrappedAxios.get('/myPath', {cache: false});
```
will have higher priority and the request won't be cached but actually performed.
In this case of course, if anything was cached before needs to be removed from the cache for this path. 
The next request performed like this:
```
wrappedAxios.get('/myPath');
```
where we don't pass the `cache` option will respect the option set in filter, so the request will be cached again.

What do you think?

**Comment by jin5354** [comment]
Thank you for your advice.
RegExp is necessary to handle some complex occasion such as `https://example.com/abc/*`. It is powerful and universal,  I think it's adequate to enable cache.  

`{cache: true}` may have a conflict risk with axios in the future. Params will be transported to axios directly, so I don't think add extra param(and parse it later, then may delete it?) in axios's config object is a good idea. This is another thinking way to make this call 'clean'. What's more, two ways to enable cache, and the priority system may be confusing.

If you want cache, write a filter, then use wrappedAxios. If you want a exception that some request shouldn't be cached or read cache, just performed, use origin axios.

btw, clearCache feature will be added in a few days, then you can clear some or All cache.
