### ISSUE TITLE
question about the lib implementing

### ISSUE THREAD

**Issue by kuitos** [jin5354/axios-cache-plugin#7]
Thanks to the author for providing such a great plugin for axios 😀

but I have some question after reading the source code:

1. according to your implementing, when I make a cached request I will never reach the interceptors and transformers. the correct implement should be based on the adapter mechanism I think.
2. the cache implementing was to simple with Map(but It doesn't matter), my recommendation is [lru-cache](https://github.com/isaacs/node-lru-cache)

**Comment by jin5354** [comment]
Thankyou! I will look into it this weekend.
